Repository TEAM-YANGBONG/DameDame-Android, pull requests merged in 2022-12, with the labels that each got.

#127 [hotfix] 캐릭터 선택 화면 관련 빌드 에러 수정 🚒
  feature/set-character/src/main/java/com/yangbong/set_character/ui/SetCharacterActivity.kt
  feature/set-character/src/main/java/com/yangbong/set_character/view/CharacterInfoBottomSheetDialog.kt
Labels: 🐻‍❄️ 원석, 🚒 hotfix

#132 [fix] remote config 버전이 불러와지지 않는 오류 수정
  feature/notification/src/main/java/com/yangbong/damedame/notification/NotificationFragment.kt
  feature/notification/src/main/java/com/yangbong/damedame/notification/NotificationViewModel.kt
  feature/notification/src/main/java/com/yangbong/damedame/notification/SettingActivity.kt
  feature/notification/src/main/java/com/yangbong/damedame/notification/UpdateDialog.kt
  feature/notification/src/main/res/drawable/dialog_background.xml
  feature/notification/src/main/res/layout/update_version_dialog.xml
  feature/notification/src/main/res/values/strings.xml
Labels: 🦊 진욱, 🔥 Pull Request, 🔮 fix

#135 [refactor] 캐릭터 설정 코드 리팩토링 ♻️
  app/src/main/java/com/yangbong/damedame/di/RetrofitModule.kt
  core-ui/build.gradle.kts
  core-ui/src/main/java/com/yangbong/core_ui/util/BindingAdapters.kt
  data/src/main/java/com/yangbong/data/remote/data_source/RemoteLoginDataSource.kt
  data/src/main/java/com/yangbong/data/remote/data_source/RemoteLoginDataSourceImpl.kt
  data/src/main/java/com/yangbong/data/remote/data_source/RemoteSentimentAnalyzeDataSource.kt
  data/src/main/java/com/yangbong/data/remote/service/LoginService.kt
  data/src/main/java/com/yangbong/data/repository/LoginRepositoryImpl.kt
  data/src/main/java/com/yangbong/data/repository/SetCharacterRepositoryImpl.kt
  domain/src/main/java/com/yangbong/domain/repository/SetCharacterRepository.kt
  feature/auth/src/main/res/layout/fragment_login.xml
  feature/main/src/main/res/layout/fragment_home.xml
  feature/set-character/build.gradle.kts
  feature/set-character/src/main/java/com/yangbong/set_character/CharacterData.kt
  feature/set-character/src/main/java/com/yangbong/set_character/SetCharacterAdapter.kt
  feature/set-character/src/main/java/com/yangbong/set_character/ui/SetCharacterActivity.kt
  feature/set-character/src/main/java/com/yangbong/set_character/ui/SetCharacterAdapter.kt
  feature/set-character/src/main/java/com/yangbong/set_character/ui/SetCharacterViewModel.kt
  feature/set-character/src/main/java/com/yangbong/set_character/view/CharacterInfoBottomSheetDialog.kt
  feature/set-character/src/main/res/layout/item_character.xml
  feature/set-character/src/main/res/layout/layout_character_info_bottom_sheet.xml
  feature/write-diary/src/main/res/layout/activity_write_diary.xml
  shared/src/main/assets/wave_1.json
  shared/src/main/assets/wave_2.json
  shared/src/main/assets/wave_3.json
  shared/src/main/assets/wave_4.json
  shared/src/main/assets/wave_5.json
  shared/src/main/assets/wave_6.json
  shared/src/main/assets/wave_7.json
  shared/src/main/assets/wave_8.json
  shared/src/main/assets/wave_9.json
  shared/src/main/res/drawable/bg_button_beige_15_dp.xml
  shared/src/main/res/drawable/bg_round_main_white_top_20_dp.xml
  shared/src/main/res/drawable/img_character_1.png
  shared/src/main/res/drawable/img_character_2.png
  shared/src/main/res/drawable/img_character_3.png
  shared/src/main/res/drawable/img_character_4.png
  shared/src/main/res/drawable/img_character_5.png
  shared/src/main/res/drawable/img_character_6.png
  shared/src/main/res/drawable/img_character_7.png
  shared/src/main/res/drawable/img_character_8.png
  shared/src/main/res/drawable/img_character_9.png
  shared/src/main/res/layout/item_character.xml
  shared/src/main/res/values/colors.xml
  shared/src/main/res/values/strings.xml
Labels: 🐻‍❄️ 원석, 🔥 Pull Request, ♻️ refactor

#137 [refactor] 일기 작성 - 리팩토링 ♻️
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/yangbong/damedame/di/RemoteDataSourceModule.kt
  app/src/main/java/com/yangbong/damedame/di/RepositoryModule.kt
  app/src/main/java/com/yangbong/damedame/di/RetrofitServiceModule.kt
  data/src/main/java/com/yangbong/data/remote/data_source/RemoteGetCharacterDataSource.kt
  data/src/main/java/com/yangbong/data/remote/data_source/RemoteGetCharacterDataSourceImpl.kt
  data/src/main/java/com/yangbong/data/remote/data_source/RemoteLoginDataSourceImpl.kt
  data/src/main/java/com/yangbong/data/remote/data_source/RemoteSentimentAnalyzeDataSourceImpl.kt
  data/src/main/java/com/yangbong/data/remote/data_source/RemoteSetProfileDataSource.kt
  data/src/main/java/com/yangbong/data/remote/data_source/RemoteSetProfileDataSourceImpl.kt
  data/src/main/java/com/yangbong/data/remote/data_source/RemoteWriteDiaryDataSource.kt
  data/src/main/java/com/yangbong/data/remote/data_source/RemoteWriteWriteDiaryDataSourceImpl.kt
  data/src/main/java/com/yangbong/data/remote/mapper/DiaryMapper.kt
  data/src/main/java/com/yangbong/data/remote/model/request/WriteDiaryRequest.kt
  data/src/main/java/com/yangbong/data/remote/model/response/Diary.kt
  data/src/main/java/com/yangbong/data/remote/model/response/EmotionTypeWithValue.kt
  data/src/main/java/com/yangbong/data/remote/model/response/LoginResponse.kt
  data/src/main/java/com/yangbong/data/remote/model/response/SignUpResponse.kt
  data/src/main/java/com/yangbong/data/remote/service/NaverClovaSentimentService.kt
  data/src/main/java/com/yangbong/data/remote/service/SignUpService.kt
  data/src/main/java/com/yangbong/data/remote/service/WriteDiaryService.kt
  data/src/main/java/com/yangbong/data/repository/HomeRepositoryImpl.kt
  data/src/main/java/com/yangbong/data/repository/LoginRepositoryImpl.kt
  data/src/main/java/com/yangbong/data/repository/SetProfileRepositoryImpl.kt
  data/src/main/java/com/yangbong/data/repository/WriteDiaryRepositoryImpl.kt
  domain/src/main/java/com/yangbong/domain/entity/request/DomainDiaryRequest.kt
  domain/src/main/java/com/yangbong/domain/entity/response/DomainLoginResponse.kt
  domain/src/main/java/com/yangbong/domain/entity/response/DomainSignUpResponse.kt
  domain/src/main/java/com/yangbong/domain/repository/SetProfileRepository.kt
  domain/src/main/java/com/yangbong/domain/repository/WriteDiaryRepository.kt
  feature/auth/src/main/java/com/yangbong/auth/login/LoginFragment.kt
  feature/auth/src/main/java/com/yangbong/auth/login/LoginViewModel.kt
  feature/set-profile/src/main/java/com/yangbong/set_profile/ui/SetProfileViewModel.kt
  feature/write-diary/src/main/java/com/yangbong/write_diary/FriendSearchRecyclerViewAdapter.kt
  feature/write-diary/src/main/java/com/yangbong/write_diary/FriendsSearchFragment.kt
  feature/write-diary/src/main/java/com/yangbong/write_diary/SearchData.kt
  feature/write-diary/src/main/java/com/yangbong/write_diary/SearchResultFragment.kt
  feature/write-diary/src/main/java/com/yangbong/write_diary/SearchResultRecyclerViewAdapter.kt
  feature/write-diary/src/main/java/com/yangbong/write_diary/WriteDiaryActivity.kt
  feature/write-diary/src/main/java/com/yangbong/write_diary/WriteDiaryViewModel.kt
  feature/write-diary/src/main/java/com/yangbong/write_diary/diary_dialog.kt
  feature/write-diary/src/main/res/layout/diary_dialog.xml
  feature/write-diary/src/main/res/layout/fragment_friend_search.xml
  feature/write-diary/src/main/res/layout/fragment_search_result.xml
  feature/write-diary/src/main/res/layout/friend_diary.xml
  feature/write-diary/src/main/res/layout/search_result_row.xml
  feature/write-diary/src/main/res/layout/search_row.xml
Labels: 🐻‍❄️ 원석, 🔥 Pull Request, ♻️ refactor

#141 feat,UI] Search Fragment layout 재구성 및 기능 구현 #140
  app/src/main/java/com/yangbong/damedame/di/RemoteDataSourceModule.kt
  app/src/main/java/com/yangbong/damedame/di/RepositoryModule.kt
  app/src/main/java/com/yangbong/damedame/di/RetrofitServiceModule.kt
  data/src/main/java/com/yangbong/data/local/data_source/LocalPreferenceUserDataSource.kt
  data/src/main/java/com/yangbong/data/local/data_source/LocalPreferenceUserDataSourceImpl.kt
  data/src/main/java/com/yangbong/data/remote/data_source/RemoteSearchSource.kt
  data/src/main/java/com/yangbong/data/remote/data_source/RemoteSearchSourceImpl.kt
  data/src/main/java/com/yangbong/data/remote/data_source/RemoteUserProfileDataSource.kt
  data/src/main/java/com/yangbong/data/remote/data_source/RemoteUserProfileDataSourceImpl.kt
  data/src/main/java/com/yangbong/data/remote/mapper/NotificationMapper.kt
  data/src/main/java/com/yangbong/data/remote/mapper/SearchMapper.kt
  data/src/main/java/com/yangbong/data/remote/model/response/SearchData.kt
  data/src/main/java/com/yangbong/data/remote/model/response/SearchResponse.kt
  data/src/main/java/com/yangbong/data/remote/model/response/UserProfileResponse.kt
  data/src/main/java/com/yangbong/data/remote/service/SearchService.kt
  data/src/main/java/com/yangbong/data/remote/service/UserProfileService.kt
  data/src/main/java/com/yangbong/data/repository/FriendsRepositoryImpl.kt
  data/src/main/java/com/yangbong/data/repository/SearchRepositoryImpl.kt
  domain/src/main/java/com/yangbong/domain/entity/ProfileInfo.kt
  domain/src/main/java/com/yangbong/domain/entity/SearchInfo.kt
  domain/src/main/java/com/yangbong/domain/entity/response/DomainSearchResponse.kt
  domain/src/main/java/com/yangbong/domain/repository/FriendsRepository.kt
  domain/src/main/java/com/yangbong/domain/repository/SearchRepository.kt
  feature/auth/src/main/java/com/yangbong/auth/AuthActivity.kt
  feature/auth/src/main/java/com/yangbong/auth/login/LoginFragment.kt
  feature/main/src/main/java/com/yangbong/main/friends/FriendsViewModel.kt
  feature/main/src/main/java/com/yangbong/main/search/FriendSearchRecyclerViewAdapter.kt
  feature/main/src/main/java/com/yangbong/main/search/SearchFragment.kt
  feature/main/src/main/java/com/yangbong/main/search/SearchResultRecyclerViewAdapter.kt
  feature/main/src/main/java/com/yangbong/main/search/SearchViewModel.kt
  feature/main/src/main/res/layout/fragment_search.xml
  feature/main/src/main/res/layout/search_result_row.xml
  feature/main/src/main/res/layout/search_row.xml
  feature/set-profile/src/main/res/layout/activity_set_profile.xml
  shared/src/main/res/drawable/bg_radius_button.xml
  shared/src/main/res/drawable/ic_frplus.png
  shared/src/main/res/drawable/ic_search.png
  shared/src/main/res/drawable/ic_setting.png
Labels: 🐯 민혁, 🔥 Pull Request, ✨ feature

#146 fix]search view model 오류 fix #145
  feature/main/src/main/java/com/yangbong/main/search/SearchFragment.kt
  feature/main/src/main/java/com/yangbong/main/search/SearchViewModel.kt
Labels: 🐻‍❄️ 원석, 🐯 민혁, 🔥 Pull Request, 🚒 hotfix

#152 [fix] Main - 내 프로필 API 연동 & 온갖 오류 전부 수정🔮
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/yangbong/damedame/di/RemoteDataSourceModule.kt
  app/src/main/java/com/yangbong/damedame/di/RetrofitServiceModule.kt
  core-ui/src/main/java/com/yangbong/core_ui/util/BindingAdapters.kt
  data/src/main/java/com/yangbong/data/local/data_source/LocalPreferenceUserDataSourceImpl.kt
  data/src/main/java/com/yangbong/data/remote/data_source/RemoteGetDiaryDataSource.kt
  data/src/main/java/com/yangbong/data/remote/data_source/RemoteGetDiaryDataSourceImpl.kt
  data/src/main/java/com/yangbong/data/remote/data_source/RemoteMyProfileDataSource.kt
  data/src/main/java/com/yangbong/data/remote/data_source/RemoteMyProfileDataSourceImpl.kt
  data/src/main/java/com/yangbong/data/remote/data_source/RemoteWriteDiaryDataSourceImpl.kt
  data/src/main/java/com/yangbong/data/remote/mapper/DiaryMapper.kt
  data/src/main/java/com/yangbong/data/remote/model/request/SignUpRequest.kt
  data/src/main/java/com/yangbong/data/remote/model/request/WriteDiaryRequest.kt
  data/src/main/java/com/yangbong/data/remote/model/response/Diary.kt
  data/src/main/java/com/yangbong/data/remote/model/response/DiaryListResponse.kt
  data/src/main/java/com/yangbong/data/remote/model/response/MyProfileResponse.kt
  data/src/main/java/com/yangbong/data/remote/model/response/UserProfileResponse.kt
  data/src/main/java/com/yangbong/data/remote/service/GetDiaryService.kt
  data/src/main/java/com/yangbong/data/remote/service/MyProfileService.kt
  data/src/main/java/com/yangbong/data/repository/FriendsRepositoryImpl.kt
  data/src/main/java/com/yangbong/data/repository/MyProfileRepositoryImpl.kt
  data/src/main/java/com/yangbong/data/repository/SetProfileRepositoryImpl.kt
  data/src/main/java/com/yangbong/data/repository/WriteDiaryRepositoryImpl.kt
  domain/src/main/java/com/yangbong/domain/entity/DiaryInfo.kt
  domain/src/main/java/com/yangbong/domain/entity/EmotionInfo.kt
  domain/src/main/java/com/yangbong/domain/entity/MyProfileInfo.kt
  domain/src/main/java/com/yangbong/domain/entity/MyProfileUser.kt
  domain/src/main/java/com/yangbong/domain/entity/request/DomainDiaryRequest.kt
  domain/src/main/java/com/yangbong/domain/repository/MyProfileRepository.kt
  feature/auth/src/main/java/com/yangbong/auth/login/LoginFragment.kt
  feature/auth/src/main/java/com/yangbong/auth/login/LoginViewModel.kt
  feature/main/src/main/java/com/yangbong/main/my_profile/DiaryAdapter.kt
  feature/main/src/main/java/com/yangbong/main/my_profile/MyProfileFragment.kt
  feature/main/src/main/java/com/yangbong/main/my_profile/MyProfileTopAdapter.kt
  feature/main/src/main/java/com/yangbong/main/my_profile/MyProfileViewModel.kt
  feature/main/src/main/res/layout/fragment_my_profile.xml
  feature/main/src/main/res/layout/item_diary.xml
  feature/main/src/main/res/layout/layout_my_profile_top.xml
  feature/write-diary/src/main/java/com/yangbong/write_diary/WriteDiaryActivity.kt
  feature/write-diary/src/main/java/com/yangbong/write_diary/WriteDiaryViewModel.kt
  shared/src/main/res/drawable/bg_button_negative_20_dp.xml
  shared/src/main/res/drawable/bg_button_neutral_20_dp.xml
  shared/src/main/res/drawable/bg_button_positive_20_dp.xml
  shared/src/main/res/drawable/img_emotion_negative.png
  shared/src/main/res/drawable/img_emotion_neutral.png
  shared/src/main/res/drawable/img_emotion_positive.png
  shared/src/main/res/values/colors.xml
Labels: 🐻‍❄️ 원석, 🔥 Pull Request, 🔮 fix

#148 [feat] Work manager를 활용한 알람 기능 (#139)
  app/src/main/java/com/yangbong/damedame/navigator/MainNavigatorImpl.kt
  buildSrc/src/main/java/Dependencies.kt
  buildSrc/src/main/java/Versions.kt
  feature/main/src/main/res/layout/fragment_home.xml
  feature/notification/build.gradle.kts
  feature/notification/src/main/java/com/yangbong/damedame/notification/NavigatorIntentObject.kt
  feature/notification/src/main/java/com/yangbong/damedame/notification/NotificationDialog.kt
  feature/notification/src/main/java/com/yangbong/damedame/notification/NotificationGenerator.kt
  feature/notification/src/main/java/com/yangbong/damedame/notification/SettingActivity.kt
  feature/notification/src/main/java/com/yangbong/damedame/notification/util/TimeUtils.kt
  feature/notification/src/main/java/com/yangbong/damedame/notification/work_manager/NotificationWorker.kt
  feature/notification/src/main/res/drawable/notification_icon.png
  feature/notification/src/main/res/layout/notification_dialog.xml
  feature/notification/src/main/res/values/strings.xml
  navigator/src/main/java/com/yangbong/damedame/navigator/Navigator.kt
  shared/src/main/res/values/themes.xml
Labels: 🦊 진욱, 🔥 Pull Request, ✨ feature

#156 [feat] Jetpack Navigation 적용 ✨ (#155)
  app/src/main/java/com/yangbong/damedame/MainActivity.kt
  app/src/main/java/com/yangbong/damedame/adapter/MainViewPagerAdapter.kt
  app/src/main/java/com/yangbong/damedame/factory/DameDameFragmentFactory.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/menu/menu_main.xml
  app/src/main/res/navigation/nav_graph.xml
  feature/main/build.gradle.kts
  feature/main/src/main/java/com/yangbong/main/my_profile/MyProfileFragment.kt
  feature/main/src/main/res/navigation/home_navigation.xml
  feature/main/src/main/res/navigation/my_profile_navigation.xml
  feature/main/src/main/res/navigation/search_navigation.xml
Labels: 🐻‍❄️ 원석, 🔥 Pull Request, ✨ feature

#157 [feat] 도감 화면 api 연동 ✨ (#153)
  app/src/main/java/com/yangbong/damedame/di/RemoteDataSourceModule.kt
  app/src/main/java/com/yangbong/damedame/di/RepositoryModule.kt
  app/src/main/java/com/yangbong/damedame/di/RetrofitServiceModule.kt
  data/src/main/java/com/yangbong/data/remote/data_source/RemotePocketDataSource.kt
  data/src/main/java/com/yangbong/data/remote/data_source/RemotePocketDataSourceImpl.kt
  data/src/main/java/com/yangbong/data/remote/mapper/CharacterMapper.kt
  data/src/main/java/com/yangbong/data/remote/model/response/Character.kt
  data/src/main/java/com/yangbong/data/remote/service/PocketService.kt
  data/src/main/java/com/yangbong/data/repository/PocketRepositoryImpl.kt
  domain/src/main/java/com/yangbong/domain/entity/CharacterInfo.kt
  domain/src/main/java/com/yangbong/domain/repository/PocketRepository.kt
  feature/main/build.gradle.kts
  feature/main/src/main/java/com/yangbong/main/friends/FriendsFragment.kt
  feature/main/src/main/java/com/yangbong/main/friends/FriendsViewModel.kt
  feature/main/src/main/java/com/yangbong/main/my_profile/MyProfileFragment.kt
  feature/main/src/main/java/com/yangbong/main/my_profile/MyProfileTopAdapter.kt
  feature/main/src/main/java/com/yangbong/main/pocket/PocketFragment.kt
  feature/main/src/main/java/com/yangbong/main/pocket/PocketViewModel.kt
  feature/main/src/main/res/layout/fragment_friends.xml
  feature/main/src/main/res/layout/fragment_pocket.xml
  feature/set-character/src/main/java/com/yangbong/set_character/ui/SetCharacterAdapter.kt
  feature/set-character/src/main/res/layout/item_character.xml
Labels: 🐻‍❄️ 원석, 🔥 Pull Request, ✨ feature

#163 [feat] 일기 조회 기능 구현 ✨ (#161)
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/yangbong/damedame/di/RemoteDataSourceModule.kt
  app/src/main/java/com/yangbong/damedame/di/RepositoryModule.kt
  app/src/main/java/com/yangbong/damedame/di/RetrofitServiceModule.kt
  app/src/main/java/com/yangbong/damedame/factory/DameDameFragmentFactory.kt
  core-ui/src/main/java/com/yangbong/core_ui/base/BindingActivity.kt
  data/src/main/java/com/yangbong/data/remote/data_source/RemoteDiaryDataSource.kt
  data/src/main/java/com/yangbong/data/remote/data_source/RemoteDiaryDataSourceImpl.kt
  data/src/main/java/com/yangbong/data/remote/model/response/DiaryResponse.kt
  data/src/main/java/com/yangbong/data/remote/service/DiaryContentService.kt
  data/src/main/java/com/yangbong/data/repository/DiaryRepositoryImpl.kt
  domain/src/main/java/com/yangbong/domain/entity/Diary.kt
  domain/src/main/java/com/yangbong/domain/repository/DiaryRepository.kt
  feature/main/src/main/java/com/yangbong/main/diary/DiaryDetailActivity.kt
  feature/main/src/main/java/com/yangbong/main/diary/DiaryDetailViewModel.kt
  feature/main/src/main/java/com/yangbong/main/my_profile/DiaryAdapter.kt
  feature/main/src/main/java/com/yangbong/main/my_profile/MyProfileFragment.kt
  feature/main/src/main/res/layout/activity_diary_detail.xml
Labels: 🐻‍❄️ 원석, 🔥 Pull Request, ✨ feature
