Repository TEAM-YANGBONG/DameDame-Android, pull requests merged in 2022-11, with the labels that each got.

#3 [feat] 프로젝트 초기 설정 (#1)
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/yangbong/damedame/DameDameApplication.kt
  app/src/main/java/com/yangbong/damedame/MainActivity.kt
  app/src/main/java/com/yangbong/damedame/di/NavigatorModule.kt
  app/src/main/java/com/yangbong/damedame/factory/DameDameFragmentFactory.kt
  app/src/main/java/com/yangbong/damedame/navigator/MainNavigatorImpl.kt
  app/src/main/res/layout/activity_main.xml
  core-ui/build.gradle.kts
  core-ui/src/main/java/com/yangbong/core_ui/base/BaseViewModel.kt
  core-ui/src/main/java/com/yangbong/core_ui/base/BindingActivity.kt
  core-ui/src/main/java/com/yangbong/core_ui/base/BindingFragment.kt
  core-ui/src/main/java/com/yangbong/core_ui/extension/ContextExtension.kt
  core-ui/src/main/java/com/yangbong/core_ui/util/Event.kt
  core-ui/src/main/java/com/yangbong/core_ui/util/Injector.kt
  navigator/.gitignore
  navigator/build.gradle.kts
  navigator/consumer-rules.pro
  navigator/proguard-rules.pro
  navigator/src/androidTest/java/com/yangbong/damedame/navigator/ExampleInstrumentedTest.kt
  navigator/src/main/AndroidManifest.xml
  navigator/src/main/java/com/yangbong/damedame/navigator/Navigator.kt
  navigator/src/test/java/com/yangbong/damedame/navigator/ExampleUnitTest.kt
  settings.gradle.kts
Labels: 🐻‍❄️ 원석, 🔥 Pull Request

#6 [hotfix] 모듈명을 friend-search 에서 search-friend로 변경 (#5)
  app/build.gradle.kts
  feature/search-friend/.gitignore
  feature/search-friend/build.gradle.kts
  feature/search-friend/consumer-rules.pro
  feature/search-friend/proguard-rules.pro
  feature/search-friend/src/androidTest/java/com/yangbong/search_friend/ExampleInstrumentedTest.kt
  feature/search-friend/src/main/AndroidManifest.xml
  feature/search-friend/src/test/java/com/yangbong/search_friend/ExampleUnitTest.kt
  settings.gradle.kts
Labels: 🐻‍❄️ 원석, 🚒 hotfix

#7 [ui] MainActivity 초기 작업 (Bottom Navigation View, Floating Action Button)
  app/src/main/res/color/selector_bottom_nav.xml
  app/src/main/res/drawable/bg_bottom_nav_white_round_15_dp.xml
  app/src/main/res/drawable/ic_home.xml
  app/src/main/res/drawable/ic_profile.xml
  app/src/main/res/drawable/ic_search.xml
  app/src/main/res/drawable/ic_write.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/menu/menu_main.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
  shared/src/main/res/values/colors.xml
  shared/src/main/res/values/dimens.xml
  shared/src/main/res/values/strings.xml
Labels: 🐻‍❄️ 원석, 🎨 ui

#9 [ui] 앱 아이콘 적용
  app/src/debug/ic_damedame_launcher-playstore.png
  app/src/debug/res/mipmap-anydpi-v26/ic_damedame_launcher.xml
  app/src/debug/res/mipmap-anydpi-v26/ic_damedame_launcher_round.xml
  app/src/debug/res/mipmap-hdpi/ic_damedame_launcher.png
  app/src/debug/res/mipmap-hdpi/ic_damedame_launcher_background.png
  app/src/debug/res/mipmap-hdpi/ic_damedame_launcher_foreground.png
  app/src/debug/res/mipmap-hdpi/ic_damedame_launcher_round.png
  app/src/debug/res/mipmap-mdpi/ic_damedame_launcher.png
  app/src/debug/res/mipmap-mdpi/ic_damedame_launcher_background.png
  app/src/debug/res/mipmap-mdpi/ic_damedame_launcher_foreground.png
  app/src/debug/res/mipmap-mdpi/ic_damedame_launcher_round.png
  app/src/debug/res/mipmap-xhdpi/ic_damedame_launcher.png
  app/src/debug/res/mipmap-xhdpi/ic_damedame_launcher_background.png
  app/src/debug/res/mipmap-xhdpi/ic_damedame_launcher_foreground.png
  app/src/debug/res/mipmap-xhdpi/ic_damedame_launcher_round.png
  app/src/debug/res/mipmap-xxhdpi/ic_damedame_launcher.png
  app/src/debug/res/mipmap-xxhdpi/ic_damedame_launcher_background.png
  app/src/debug/res/mipmap-xxhdpi/ic_damedame_launcher_foreground.png
  app/src/debug/res/mipmap-xxhdpi/ic_damedame_launcher_round.png
  app/src/debug/res/mipmap-xxxhdpi/ic_damedame_launcher.png
  app/src/debug/res/mipmap-xxxhdpi/ic_damedame_launcher_background.png
  app/src/debug/res/mipmap-xxxhdpi/ic_damedame_launcher_foreground.png
  app/src/debug/res/mipmap-xxxhdpi/ic_damedame_launcher_round.png
  app/src/main/AndroidManifest.xml
  shared/src/main/res/values/strings.xml
Labels: 🐻‍❄️ 원석, 🎨 ui

#12 [feat] 타이틀바 없애기 / 상태바 기본 색상 적용 (#11)
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/values/themes.xml
  shared/src/main/res/drawable/shape_rect_white_fill_top_20.xml
  shared/src/main/res/values/colors.xml
  shared/src/main/res/values/dimens.xml
Labels: 🐻‍❄️ 원석, 🔥 Pull Request

#19 [hotfix] character 관련 리소스 및 레이아웃 파일 auth 모듈로 이동 (#18)
  feature/auth/src/main/res/drawable/popup_layout_bg.xml
  feature/auth/src/main/res/drawable/popup_layout_button_bg.xml
  feature/auth/src/main/res/drawable/set_profile_button_bg.xml
  feature/auth/src/main/res/layout/character_popup.xml
  feature/auth/src/main/res/layout/login.xml
  feature/auth/src/main/res/layout/set_character.xml
  feature/auth/src/main/res/layout/set_profile.xml
  feature/auth/src/main/res/layout/splash.xml
  feature/set-profile/src/main/res/drawable-v24/character_brown.png
  feature/set-profile/src/main/res/drawable-v24/character_cloud.png
  feature/set-profile/src/main/res/drawable-v24/character_dark.png
  feature/set-profile/src/main/res/drawable-v24/character_deeppink.png
  feature/set-profile/src/main/res/drawable-v24/character_green.png
  feature/set-profile/src/main/res/drawable-v24/character_grey.png
  feature/set-profile/src/main/res/drawable-v24/character_pastelpink.png
  feature/set-profile/src/main/res/drawable-v24/character_white.png
  feature/set-profile/src/main/res/drawable-v24/character_yellow.png
  feature/set-profile/src/main/res/drawable-v24/kakao_login_medium_narrow.png
  shared/src/main/res/drawable/img_character_01.png
  shared/src/main/res/drawable/img_character_02.png
  shared/src/main/res/drawable/img_character_03.png
  shared/src/main/res/drawable/img_character_04.png
  shared/src/main/res/drawable/img_character_05.png
  shared/src/main/res/drawable/img_character_06.png
  shared/src/main/res/drawable/img_character_07.png
  shared/src/main/res/drawable/img_character_08.png
  shared/src/main/res/drawable/img_character_09.png
  shared/src/main/res/font/jua.ttf
Labels: 🐻‍❄️ 원석, 🔥 Pull Request, 🚒 hotfix

#26 [hotfix] 캐릭터 레이아웃 수정 (#25)
  feature/auth/src/main/res/drawable/ic_camera.xml
  feature/auth/src/main/res/layout/activity_login.xml
  feature/auth/src/main/res/layout/character_popup.xml
  feature/auth/src/main/res/layout/fragment_select_character.xml
  feature/auth/src/main/res/layout/fragment_set_profile.xml
  feature/auth/src/main/res/layout/item_character.xml
  feature/auth/src/main/res/layout/login.xml
  feature/auth/src/main/res/layout/set_character.xml
  feature/auth/src/main/res/layout/set_profile.xml
  feature/auth/src/main/res/layout/splash.xml
  shared/src/main/res/drawable/bg_button_gray_15_dp.xml
  shared/src/main/res/drawable/bg_button_pink_15_dp.xml
  shared/src/main/res/drawable/bg_button_yellow_15_dp.xml
  shared/src/main/res/drawable/ic_back.xml
  shared/src/main/res/drawable/ic_close.xml
  shared/src/main/res/drawable/ic_kakao_logo.png
  shared/src/main/res/drawable/img_profile_tmp_01.png
  shared/src/main/res/values/colors.xml
  shared/src/main/res/values/strings.xml
  shared/src/main/res/values/themes.xml
Labels: 🐻‍❄️ 원석, 🔥 Pull Request, 🚒 hotfix, 🎨 ui

#24 [UI] 환경설정을 위한 화면 구성
  feature/notification/src/main/res/layout/activity_setting.xml
  feature/notification/src/main/res/layout/fragment_notification.xml
  feature/notification/src/main/res/layout/item_setting.xml
  feature/notification/src/main/res/layout/recycler_item_notification.xml
  shared/src/main/res/drawable/img_approve_friend_request.png
  shared/src/main/res/drawable/img_backbutton.png
  shared/src/main/res/drawable/img_bell.png
  shared/src/main/res/drawable/img_emotion_positive.png
  shared/src/main/res/drawable/img_friend_request.png
  shared/src/main/res/drawable/img_leftarrow.png
  shared/src/main/res/drawable/img_write_diary_request.png
  shared/src/main/res/drawable/shape_rect_white_fill_10.xml
Labels: 🦊 진욱, 🎨 ui

#21 [UI] 검색 , 일기 작성 부분 UI write-diary 모듈로 이동
  feature/write-diary/src/main/res/drawable/edittext.xml
  feature/write-diary/src/main/res/drawable/ic_baseline_arrow_back_24.xml
  feature/write-diary/src/main/res/drawable/img.png
  feature/write-diary/src/main/res/drawable/img_1.png
  feature/write-diary/src/main/res/layout/friend_diary.xml
  feature/write-diary/src/main/res/layout/search_friend.xml
  feature/write-diary/src/main/res/layout/search_result.xml
  feature/write-diary/src/main/res/layout/search_result_row.xml
  feature/write-diary/src/main/res/layout/search_row.xml
  feature/write-diary/src/main/res/layout/write_diary.xml
Labels: 🐯 민혁, 🎨 ui

#31 [feat] 카카오 로그인 연동 (#28)
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/yangbong/damedame/DameDameApplication.kt
  app/src/main/java/com/yangbong/damedame/di/LocalDataSourceModule.kt
  app/src/main/java/com/yangbong/damedame/di/LocalPreferencesModule.kt
  build.gradle.kts
  buildSrc/src/main/java/Versions.kt
  core-ui/build.gradle.kts
  core-ui/src/main/java/com/yangbong/core_ui/util/DameDameDebugTree.kt
  data/build.gradle.kts
  data/src/main/java/com/yangbong/data/local/datasource/LocalPreferenceUserDataSource.kt
  data/src/main/java/com/yangbong/data/local/datasource/LocalPreferenceUserDataSourceImpl.kt
  feature/auth/build.gradle.kts
  feature/auth/src/main/java/com/yangbong/auth/AuthActivity.kt
  feature/auth/src/main/java/com/yangbong/auth/KakaoLoginManager.kt
  feature/auth/src/main/java/com/yangbong/auth/LoginViewModel.kt
  feature/auth/src/main/res/layout/activity_auth.xml
  feature/auth/src/main/res/layout/fragment_login.xml
  feature/main/build.gradle.kts
  feature/notification/build.gradle.kts
  feature/write-diary/build.gradle.kts
  shared/src/main/res/values/strings.xml
Labels: 🐻‍❄️ 원석, ✨ feature

#33 [feat] Splash Screens API 적용 등 auth 모듈 초기 설정 (#10)
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/yangbong/damedame/MainActivity.kt
  app/src/main/java/com/yangbong/damedame/di/UseCaseModule.kt
  app/src/main/java/com/yangbong/damedame/navigator/MainNavigatorImpl.kt
  core-ui/src/main/java/com/yangbong/core_ui/base/BindingActivity.kt
  core-ui/src/main/java/com/yangbong/core_ui/base/BindingFragment.kt
  core-ui/src/main/java/com/yangbong/core_ui/extension/ActivityExtension.kt
  core-ui/src/main/java/com/yangbong/core_ui/util/EventFlow.kt
  core-ui/src/main/java/com/yangbong/core_ui/util/EventObserver.kt
  core-ui/src/main/java/com/yangbong/core_ui/util/Injector.kt
  data/src/main/java/com/yangbong/data/di/LoginDataModule.kt
  data/src/main/java/com/yangbong/data/local/datasource/LocalPreferenceUserDataSource.kt
  data/src/main/java/com/yangbong/data/local/datasource/LocalPreferenceUserDataSourceImpl.kt
  data/src/main/java/com/yangbong/data/repository/LoginRepositoryImpl.kt
  domain/build.gradle.kts
  domain/src/main/java/com/yangbong/domain/MyClass.kt
  domain/src/main/java/com/yangbong/domain/repository/LoginRepository.kt
  domain/src/main/java/com/yangbong/domain/use_case/login/GetAccessToken.kt
  domain/src/main/java/com/yangbong/domain/use_case/login/GetIsFirstVisited.kt
  domain/src/main/java/com/yangbong/domain/use_case/login/LoginUseCases.kt
  domain/src/main/java/com/yangbong/domain/use_case/login/SaveAccessToken.kt
  domain/src/main/java/com/yangbong/domain/use_case/login/SaveUserNickname.kt
  domain/src/main/java/com/yangbong/domain/use_case/login/SaveUserProfileImageUrl.kt
  domain/src/main/java/com/yangbong/domain/use_case/login/SetIsFirstVisited.kt
  feature/auth/build.gradle.kts
  feature/auth/src/main/java/com/yangbong/auth/AuthActivity.kt
  feature/auth/src/main/java/com/yangbong/auth/LoginViewModel.kt
  feature/auth/src/main/java/com/yangbong/auth/login/AutoLoginConstant.kt
  feature/auth/src/main/java/com/yangbong/auth/login/LoginFragment.kt
  feature/auth/src/main/java/com/yangbong/auth/login/LoginViewModel.kt
  feature/auth/src/main/java/com/yangbong/auth/social_login_manager/KakaoLoginManager.kt
  feature/auth/src/main/res/anim/logo_scale.xml
  feature/auth/src/main/res/layout/fragment_login.xml
  feature/notification/build.gradle.kts
  feature/write-diary/src/main/res/layout/activity_write_diary.xml
  feature/write-diary/src/main/res/layout/write_diary.xml
  navigator/src/main/java/com/yangbong/damedame/navigator/Navigator.kt
  shared/src/main/assets/login_planet.json
  shared/src/main/res/drawable/ic_logo.png
  shared/src/main/res/values/themes.xml
Labels: 🐻‍❄️ 원석, 🔥 Pull Request, ✨ feature

#35 [feat] Auth - Login 비즈니스 로직 구현 (#32)
  app/build.gradle.kts
  app/src/main/java/com/yangbong/damedame/MainActivity.kt
  app/src/main/java/com/yangbong/damedame/di/LocalDataSourceModule.kt
  app/src/main/java/com/yangbong/damedame/di/RemoteDataSourceModule.kt
  app/src/main/java/com/yangbong/damedame/di/RepositoryModule.kt
  app/src/main/java/com/yangbong/damedame/di/RetrofitModule.kt
  app/src/main/java/com/yangbong/damedame/di/RetrofitServiceModule.kt
  app/src/main/java/com/yangbong/damedame/di/UseCaseModule.kt
  app/src/main/java/com/yangbong/damedame/di/annotations/NetworkLibraryAnnotations.kt
  core-data/.gitignore
  core-data/build.gradle.kts
  core-data/consumer-rules.pro
  core-data/proguard-rules.pro
  core-data/src/androidTest/java/com/yangbong/core_data/ExampleInstrumentedTest.kt
  core-data/src/main/AndroidManifest.xml
  core-data/src/main/java/com/yangbong/core_data/exception/RetrofitFailureStateException.kt
  core-data/src/test/java/com/yangbong/core_data/ExampleUnitTest.kt
  core-ui/src/main/java/com/yangbong/core_ui/extension/ViewExtension.kt
  data/build.gradle.kts
  data/src/main/java/com/yangbong/data/di/LoginDataModule.kt
  data/src/main/java/com/yangbong/data/local/data_source/LocalPreferenceUserDataSource.kt
  data/src/main/java/com/yangbong/data/local/data_source/LocalPreferenceUserDataSourceImpl.kt
  data/src/main/java/com/yangbong/data/remote/call_adapter/CustomCall.kt
  data/src/main/java/com/yangbong/data/remote/call_adapter/CustomCallAdapter.kt
  data/src/main/java/com/yangbong/data/remote/call_adapter/CustomCallAdapterFactory.kt
  data/src/main/java/com/yangbong/data/remote/call_adapter/NetworkState.kt
  data/src/main/java/com/yangbong/data/remote/data_source/RemoteLoginDataSource.kt
  data/src/main/java/com/yangbong/data/remote/data_source/RemoteLoginDataSourceImpl.kt
  data/src/main/java/com/yangbong/data/remote/model/request/LoginRequest.kt
  data/src/main/java/com/yangbong/data/remote/model/response/BaseResponse.kt
  data/src/main/java/com/yangbong/data/remote/model/response/LoginResponse.kt
  data/src/main/java/com/yangbong/data/remote/service/LoginService.kt
  data/src/main/java/com/yangbong/data/repository/LoginRepositoryImpl.kt
  domain/src/main/java/com/yangbong/domain/entity/request/DomainLoginRequest.kt
  domain/src/main/java/com/yangbong/domain/entity/response/DomainLoginResponse.kt
  domain/src/main/java/com/yangbong/domain/repository/LoginRepository.kt
  domain/src/main/java/com/yangbong/domain/use_case/login/LoginUseCases.kt
  domain/src/main/java/com/yangbong/domain/use_case/login/PostLogin.kt
  feature/auth/build.gradle.kts
  feature/auth/src/main/java/com/yangbong/auth/login/LoginViewModel.kt
  feature/main/src/main/java/com/yangbong/main/home/HomeFragment.kt
  feature/main/src/main/java/com/yangbong/main/search/SearchFragment.kt
  settings.gradle.kts
Labels: 🐻‍❄️ 원석, 🔥 Pull Request, ✨ feature

#36 [feat] fcm 기초 셋팅 (#34)
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/yangbong/damedame/DameDameApplication.kt
  app/src/main/java/com/yangbong/damedame/DameDameMessagingService.kt
  app/src/main/java/com/yangbong/damedame/di/FirebaseTokenManagerModule.kt
  app/src/main/java/com/yangbong/damedame/di/RetrofitModule.kt
  app/src/main/java/com/yangbong/damedame/di/UseCaseModule.kt
  app/src/main/java/com/yangbong/damedame/fcm/FirebaseTokenManagerImpl.kt
  core-data/src/main/java/com/yangbong/core_data/fcm/FirebaseTokenManager.kt
  data/src/main/java/com/yangbong/data/remote/model/request/LoginRequest.kt
  data/src/main/java/com/yangbong/data/remote/model/response/LoginResponse.kt
  data/src/main/java/com/yangbong/data/repository/LoginRepositoryImpl.kt
  domain/src/main/java/com/yangbong/domain/entity/request/DomainLoginRequest.kt
  domain/src/main/java/com/yangbong/domain/entity/response/DomainLoginResponse.kt
  domain/src/main/java/com/yangbong/domain/repository/LoginRepository.kt
  domain/src/main/java/com/yangbong/domain/use_case/login/GetFcmToken.kt
  domain/src/main/java/com/yangbong/domain/use_case/login/LoginUseCases.kt
  feature/auth/src/main/java/com/yangbong/auth/login/LoginFragment.kt
  feature/auth/src/main/java/com/yangbong/auth/login/LoginViewModel.kt
Labels: 🐻‍❄️ 원석, 🦊 진욱, 🔥 Pull Request, ✨ feature

#68 [UI] recycler view , row 연결 #23
  feature/write-diary/src/main/java/com/yangbong/write_diary/FriendSearchRecyclerViewAdapter.kt
  feature/write-diary/src/main/java/com/yangbong/write_diary/FriendsSearchFragment.kt
  feature/write-diary/src/main/java/com/yangbong/write_diary/SearchData.kt
  feature/write-diary/src/main/java/com/yangbong/write_diary/SearchResultFragment.kt
  feature/write-diary/src/main/java/com/yangbong/write_diary/SearchResultRecyclerViewAdapter.kt
  feature/write-diary/src/main/res/drawable/img_2.png
  feature/write-diary/src/main/res/layout/activity_write_diary.xml
  feature/write-diary/src/main/res/layout/fragment_friend_search.xml
  feature/write-diary/src/main/res/layout/fragment_search_result.xml
  feature/write-diary/src/main/res/layout/friend_diary.xml
  feature/write-diary/src/main/res/layout/search_result_row.xml
  feature/write-diary/src/main/res/layout/search_row.xml
Labels: 🔥 Pull Request, 🎨 ui

#69 [ui] recycler view, activity, fragment를 위한 class 파일 추가 (#46)
  feature/notification/src/main/AndroidManifest.xml
  feature/notification/src/main/java/com/yangbong/damedame/notification/NotificationFragment.kt
  feature/notification/src/main/java/com/yangbong/damedame/notification/NotificationRecyclerViewAdapter.kt
  feature/notification/src/main/java/com/yangbong/damedame/notification/SettingActivity.kt
  feature/notification/src/main/java/com/yangbong/damedame/notification/SettingRecyclerViewAdapter.kt
  feature/notification/src/main/res/layout/recycler_item_setting.xml
  feature/notification/src/main/res/values/strings.xml
Labels: 🔥 Pull Request, 🎨 ui

#89 [chore] 네이버 CLOVA Sentiment API 연동 🧩
  app/build.gradle.kts
  app/src/main/java/com/yangbong/damedame/di/RetrofitModule.kt
  app/src/main/java/com/yangbong/damedame/di/RetrofitServiceModule.kt
  app/src/main/java/com/yangbong/damedame/di/annotations/NetworkLibraryAnnotations.kt
  data/src/main/java/com/yangbong/data/remote/data_source/RemoteSentimentAnalyzeDataSource.kt
  data/src/main/java/com/yangbong/data/remote/data_source/RemoteSentimentAnalyzeDataSourceImpl.kt
  data/src/main/java/com/yangbong/data/remote/model/request/SentimentAnalyzeRequest.kt
  data/src/main/java/com/yangbong/data/remote/model/response/LoginResponse.kt
  data/src/main/java/com/yangbong/data/remote/model/response/SentimentAnalyzeResponse.kt
  data/src/main/java/com/yangbong/data/remote/service/NaverBookSearchService.kt
  data/src/main/java/com/yangbong/data/repository/LoginRepositoryImpl.kt
Labels: 🐻‍❄️ 원석, 🧩 chore

#91 [ui] 도감 화면 레이아웃 작업 (#90)
  feature/main/src/main/java/com/yangbong/main/my_profile/MyProfileFragment.kt
  feature/main/src/main/java/com/yangbong/main/pocket/PocketFragment.kt
  feature/main/src/main/java/com/yangbong/main/pocket/PocketViewModel.kt
  feature/main/src/main/res/layout/fragment_pocket.xml
  shared/src/main/res/drawable/ic_share.xml
  shared/src/main/res/layout/item_character.xml
Labels: 🐻‍❄️ 원석, 🔥 Pull Request, 🎨 ui

#95 [ui] 친구 목록 화면 레이아웃 작업 🎨 (#94)
  feature/main/src/main/java/com/yangbong/main/friends/FriendsFragment.kt
  feature/main/src/main/java/com/yangbong/main/friends/FriendsViewModel.kt
  feature/main/src/main/res/layout/fragment_friends.xml
  feature/main/src/main/res/layout/item_friend.xml
  shared/src/main/res/drawable/ic_visit.xml
  shared/src/main/res/values/strings.xml
Labels: 🐻‍❄️ 원석, 🎨 ui

#82 [feat] remote config를 활용한 버전 확인 #80
  feature/notification/src/main/java/com/yangbong/damedame/notification/SettingActivity.kt
  feature/notification/src/main/java/com/yangbong/damedame/notification/SettingRecyclerViewAdapter.kt
  feature/notification/src/main/java/com/yangbong/damedame/notification/SettingViewModel.kt
  feature/notification/src/main/res/layout/activity_setting.xml
  feature/notification/src/main/res/layout/recycler_item_setting.xml
  shared/src/main/res/drawable/img_app_version.png
  shared/src/main/res/drawable/img_security_policy.png
  shared/src/main/res/values/strings.xml
Labels: 🦊 진욱, 🔥 Pull Request, ✨ feature

#100 [feat] MyProfileTopAdapter에 도감, 친구 클릭 리스너 연동 (#98)
  feature/main/src/main/java/com/yangbong/main/my_profile/MyProfileFragment.kt
  feature/main/src/main/java/com/yangbong/main/my_profile/MyProfileTopAdapter.kt
Labels: 🔥 Pull Request, ✨ feature

#102 [fix] Auth - 회원가입 API 연동 (#101)
  data/src/main/java/com/yangbong/data/remote/model/request/LoginRequest.kt
  data/src/main/java/com/yangbong/data/remote/model/response/BaseResponse.kt
  data/src/main/java/com/yangbong/data/remote/model/response/LoginResponse.kt
  data/src/main/java/com/yangbong/data/remote/service/LoginService.kt
  data/src/main/java/com/yangbong/data/repository/LoginRepositoryImpl.kt
  domain/src/main/java/com/yangbong/domain/entity/request/DomainLoginRequest.kt
  feature/auth/src/main/java/com/yangbong/auth/login/LoginFragment.kt
  feature/auth/src/main/java/com/yangbong/auth/login/LoginViewModel.kt
Labels: 🐻‍❄️ 원석, 🔥 Pull Request, 🔮 fix

#111 [feat] SetProfile - 프로필 이미지 가져오기 & BottomSheetDialog 구현 ✨ (#105)
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/yangbong/damedame/di/RetrofitServiceModule.kt
  app/src/main/java/com/yangbong/damedame/navigator/MainNavigatorImpl.kt
  core-ui/src/main/java/com/yangbong/core_ui/base/BaseViewModel.kt
  data/src/main/java/com/yangbong/data/remote/data_source/RemoteAwsStorageDataSource.kt
  data/src/main/java/com/yangbong/data/remote/data_source/RemoteSetProfileDataSourceImpl.kt
  data/src/main/java/com/yangbong/data/remote/service/CheckDuplicateProfileNicknameService.kt
  feature/auth/src/main/java/com/yangbong/auth/login/LoginViewModel.kt
  feature/set-profile/src/main/java/com/yangbong/set_profile/ui/SetProfileActivity.kt
  feature/set-profile/src/main/java/com/yangbong/set_profile/ui/SetProfileViewModel.kt
  feature/set-profile/src/main/java/com/yangbong/set_profile/view/ImageBottomSheetDialog.kt
  feature/set-profile/src/main/res/layout/activity_set_profile.xml
  shared/src/main/res/drawable/bg_round_white_top_20_dp.xml
  shared/src/main/res/layout/layout_image_bottom_sheet.xml
  shared/src/main/res/values/strings.xml
  shared/src/main/res/values/themes.xml
Labels: 🐻‍❄️ 원석, 🔥 Pull Request, ✨ feature

#112 [chore] AWS Mobile SDK for Android 초기 셋팅 🧩
  amplify/.config/project-config.json
  amplify/backend/auth/damedameandroida0eb78dd/cli-inputs.json
  amplify/backend/backend-config.json
  amplify/backend/storage/S3DameDame/cli-inputs.json
  amplify/backend/types/amplify-dependent-resources-ref.d.ts
  amplify/team-provider-info.json
  app/build.gradle.kts
  app/src/main/java/com/yangbong/damedame/DameDameApplication.kt
  buildSrc/src/main/java/Constants.kt
  buildSrc/src/main/java/Dependencies.kt
  buildSrc/src/main/java/Versions.kt
Labels: 🐻‍❄️ 원석, 🔥 Pull Request, 🧩 chore

#86 [Feat]write diary activity 기능 구현 #63
  data/src/main/java/com/yangbong/data/remote/model/request/WriteDiaryRequest.kt
  data/src/main/java/com/yangbong/data/remote/service/WriteDiaryService.kt
  feature/write-diary/src/main/java/com/yangbong/write_diary/WriteDiaryActivity.kt
  feature/write-diary/src/main/java/com/yangbong/write_diary/diary_dialog.kt
  feature/write-diary/src/main/res/drawable/dialog.xml
  feature/write-diary/src/main/res/layout/activity_write_diary.xml
  feature/write-diary/src/main/res/layout/diary_dialog.xml
  shared/src/main/res/values/colors.xml
  shared/src/main/res/values/themes.xml
Labels: 🐯 민혁, 🔥 Pull Request, ✨ feature

#115 [feat] 카메라 권한 요청 & AWS S3 Storage 이미지 업로드 로직 구현 ✨
  app/src/main/java/com/yangbong/damedame/DameDameApplication.kt
  buildSrc/src/main/java/Dependencies.kt
  buildSrc/src/main/java/Versions.kt
  core-ui/src/main/java/com/yangbong/core_ui/base/BindingActivity.kt
  core-ui/src/main/java/com/yangbong/core_ui/util/BindingAdapters.kt
  data/build.gradle.kts
  data/src/main/java/com/yangbong/data/remote/data_source/RemoteAwsStorageDataSource.kt
  data/src/main/java/com/yangbong/data/repository/SetProfileRepositoryImpl.kt
  domain/src/main/java/com/yangbong/domain/repository/SetProfileRepository.kt
  feature/set-profile/build.gradle.kts
  feature/set-profile/src/main/java/com/yangbong/set_profile/ui/SetProfileActivity.kt
  feature/set-profile/src/main/java/com/yangbong/set_profile/ui/SetProfileViewModel.kt
  feature/set-profile/src/main/res/layout/activity_set_profile.xml
Labels: 🐻‍❄️ 원석, 🔥 Pull Request, ✨ feature

#119 [feat] 프로필 설정 -> 캐릭터 선택 이동 로직 구현 ✨ #116
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/yangbong/damedame/navigator/MainNavigatorImpl.kt
  feature/set-character/src/main/java/com/yangbong/set_character/SetCharacterViewModel.kt
  feature/set-profile/src/main/java/com/yangbong/set_profile/ui/SetProfileActivity.kt
  feature/set-profile/src/main/java/com/yangbong/set_profile/ui/SetProfileViewModel.kt
  navigator/src/main/java/com/yangbong/damedame/navigator/Navigator.kt
Labels: 🔥 Pull Request, ✨ feature

#121 [hotfix] 프로필 설정 관련 hilt 에러 수정 (#120)
  app/src/main/java/com/yangbong/damedame/di/RepositoryModule.kt
  app/src/main/java/com/yangbong/damedame/di/RetrofitServiceModule.kt
  data/src/main/java/com/yangbong/data/repository/SetCharacterRepositoryImpl.kt
  feature/set-character/src/main/java/com/yangbong/set_character/SetCharacterViewModel.kt
Labels: 🐻‍❄️ 원석, 🔥 Pull Request, 🚒 hotfix

#123 [ui] set-character Dialog #83
  feature/set-character/src/main/java/com/yangbong/set_character/CharacterData.kt
  feature/set-character/src/main/java/com/yangbong/set_character/SelectedCharacterSheetDialog.kt
  feature/set-character/src/main/java/com/yangbong/set_character/SetCharacterActivity.kt
  feature/set-character/src/main/java/com/yangbong/set_character/SetCharacterAdapter.kt
  feature/set-character/src/main/java/com/yangbong/set_character/SetCharacterViewModel.kt
  feature/set-character/src/main/res/layout/activity_set_character.xml
  shared/src/main/res/layout/layout_selected_character_sheet.xml
Labels: 🚀 윤혁, 🎨 ui

#107 [refactor] Notification Fragment에 존재하는 recycler view에 대해서 databinding 적용하기 #99
  app/src/main/java/com/yangbong/damedame/di/RemoteDataSourceModule.kt
  app/src/main/java/com/yangbong/damedame/di/RepositoryModule.kt
  app/src/main/java/com/yangbong/damedame/di/RetrofitServiceModule.kt
  data/src/main/java/com/yangbong/data/remote/data_source/RemoteNotificationDataSource.kt
  data/src/main/java/com/yangbong/data/remote/data_source/RemoteNotificationDataSourceImpl.kt
  data/src/main/java/com/yangbong/data/remote/mapper/NotificationMapper.kt
  data/src/main/java/com/yangbong/data/remote/model/request/NotificationRequest.kt
  data/src/main/java/com/yangbong/data/remote/model/response/Notification.kt
  data/src/main/java/com/yangbong/data/remote/model/response/NotificationResponse.kt
  data/src/main/java/com/yangbong/data/remote/service/NotificationService.kt
  data/src/main/java/com/yangbong/data/repository/NotificationRepositoryImpl.kt
  domain/src/main/java/com/yangbong/domain/entity/NotificationInfo.kt
  domain/src/main/java/com/yangbong/domain/entity/request/DomainNotificationRequest.kt
  domain/src/main/java/com/yangbong/domain/entity/response/DomainNotificationResponse.kt
  domain/src/main/java/com/yangbong/domain/repository/NotificationRepository.kt
  feature/notification/src/main/java/com/yangbong/damedame/notification/NotificationFragment.kt
  feature/notification/src/main/java/com/yangbong/damedame/notification/NotificationRecyclerViewAdapter.kt
  feature/notification/src/main/java/com/yangbong/damedame/notification/NotificationViewModel.kt
  feature/notification/src/main/java/com/yangbong/damedame/notification/SettingRecyclerViewAdapter.kt
  feature/notification/src/main/java/com/yangbong/damedame/notification/SettingViewModel.kt
  feature/notification/src/main/java/com/yangbong/damedame/notification/data/EmotionType.kt
  feature/notification/src/main/java/com/yangbong/damedame/notification/data/NotificationData.kt
  feature/notification/src/main/java/com/yangbong/damedame/notification/data/NotificationType.kt
  feature/notification/src/main/java/com/yangbong/damedame/notification/util/BindingAdapter.kt
  feature/notification/src/main/res/layout/fragment_notification.xml
  feature/notification/src/main/res/layout/recycler_item_notification.xml
  shared/src/main/res/values/strings.xml
Labels: 🦊 진욱, 🔥 Pull Request

#125 [fix] 캐릭터 설정 팝업, 어댑터 관련 수정 🔮
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/yangbong/damedame/navigator/MainNavigatorImpl.kt
  domain/src/main/java/com/yangbong/domain/entity/CharacterInfo.kt
  feature/set-character/src/main/java/com/yangbong/set_character/ui/SetCharacterActivity.kt
  feature/set-character/src/main/java/com/yangbong/set_character/ui/SetCharacterAdapter.kt
  feature/set-character/src/main/java/com/yangbong/set_character/ui/SetCharacterViewModel.kt
  feature/set-character/src/main/java/com/yangbong/set_character/view/SelectedCharacterSheetDialog.kt
  feature/set-character/src/main/res/layout/activity_set_character.xml
  feature/set-character/src/main/res/layout/item_character.xml
  feature/set-character/src/main/res/layout/layout_character_info_bottom_sheet.xml
  shared/src/main/res/layout/layout_selected_character_sheet.xml
  shared/src/main/res/values/strings.xml
Labels: 🐻‍❄️ 원석, 🔥 Pull Request, 🔮 fix
